name: Feature Request
description: Suggest a new feature or enhancement for kube-changejob
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem or use case.
      placeholder: "I'm frustrated when... / I need to be able to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, provide an example of how this feature would be used (e.g., ChangeJob manifest, command line usage, etc.)
      placeholder: |
        apiVersion: changejob.nusnewob.dev/v1alpha1
        kind: ChangeJob
        metadata:
          name: example-with-new-feature
        spec:
          # new feature usage here
      render: yaml
    validations:
      required: false

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Are you willing to contribute?
      description: Would you be willing to submit a pull request for this feature?
      options:
        - "Yes, I'd like to implement this"
        - "Yes, with guidance"
        - "No, but I can help with testing"
        - "No"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
